---
title: "PPOL 563 - Project - Fall 2020"
author: "Digvijay Ghotane"
date: "12/6/2020"
output:
  pdf_document: default
  html_document: default
---
```{r setup, include = FALSE}
knitr::opts_chunk$set(eval = FALSE) ## added to not run code during knit
```
Replication Code

```{r error=F, message=FALSE, warning=FALSE}
library(tidyverse)
library(plotly)
library(anytime) ## For dates and time
library(lubridate) ## For dates and time
## For plotting DC by Ward
library(DCmapR) ## https://github.com/BingoLaHaye/DCmapR/ 
## For plotting DC by Ward
library(zoo)
library(gganimate)
library(transformr)
library(viridis)
library(gifski) ## To export as gif from gganimate
```

```{r message=F, error=F, warning=F}
## Uploading to Plotly servers
Sys.setenv("plotly_username" = "digvijayghotane")
Sys.setenv("plotly_api_key" = "key_retracted")
```


# Figure 1
Data from Bureau of Labor Statistics: https://beta.bls.gov/dataViewer/view/timeseries/LASST110000000000003

```{r message = F, error = F, warning = F}
unemp = read_csv("file.csv")

x = unemp %>% 
  mutate(Label = anydate(Label),
         Label = lubridate::ymd(Label)) %>% 
  filter(Label > as.Date("2018-02-01")) %>% 
  select(Date = Label,
         "Unemployment Rate (in %)" = Value) %>% 
  ggplot(aes(x = Date, y = `Unemployment Rate (in %)`, group = 1)) +
  geom_line() +
  geom_point(color = "darkred") +
  annotate("text", x = as.Date("2019-11-01"), y = 11, 
           label = "~6% increase in\nunemployment rate from\nMarch 2020 to April 2020",
           size = 3.5, family = "Times New Roman") +
  scale_x_date(date_breaks = "3 month",
               date_labels = '%b %Y',
               expand = c(0,0)) +
  labs(title='Unemployment Rate (in percentage) in the District of Columbia',
       subtitle = 'From March 2018 to November 2020',
       caption = 'Source: Bureau of Labor Statistics') +
  theme(panel.background = element_rect(fill = "white", 
                                        colour = "gray", 
                                        size = 1),
        panel.grid = element_blank(),
        plot.background = element_rect(fill = "white", 
                                       colour = "black", 
                                       size = 2),
        axis.title = element_text(color = 'black', 
                                   size = 12, 
                                   family = 'Times New Roman'),
        
        axis.text = element_text(color = 'black', 
                                   size = 10, 
                                   family = 'Times New Roman',
                                   angle = 0),
        axis.text.y = element_text(size = 11),
        plot.title = element_text(
          family = 'Times New Roman', 
                                  size = 15, color = 'black', 
                                  face = 'bold',
                                  hjust = 0.5),
        plot.subtitle = element_text(
          family = 'Times New Roman', 
          size = 11, 
                                     color = 'black', 
                                     face = 'italic', 
                                     hjust = 0.5),
        plot.caption = element_text(family = 'Times New Roman', 
                                    size = 9, 
                                    color = 'black', 
                                    face = 'italic', 
                                    hjust = 1),
        legend.title= element_text(family = 'Times New Roman', 
                                    size = 12, 
                                    color = 'black',
                                    hjust = 1),
        legend.text = element_text(family = 'Times New Roman', 
                                    size = 9, 
                                    color = 'black',
                                    hjust = 1))

x = ggplotly(x) %>% 
  layout(annotations = list(x = 1, y = -0.1, 
                            text = "Source: Bureau of Labor Statistics", 
      showarrow = F, xref='paper', yref='paper', 
      xanchor='right', yanchor='auto', xshift=0, yshift=0,
      font=list(size=12)),
      title = list(text = paste0('Unemployment Rate in the District of Columbia',
                                    '<br>',
                                    '<sup>',
                                    'From March 2018 to November 2020',
                                    '</sup>')))

api_create(x, filename = "ppol563_final_project_figure1") ## Few edits made online

## Link to online graph on Plotly's Chart Studio: https://plotly.com/~digvijayghotane/1/ 
```


# Figure 2
Data from Open Data DC: https://opendata.dc.gov/datasets/dc-covid-19-cases-by-ward
```{r message=F, error=F, warning=F}
Wardlabs = get_centroid(Ward = TRUE)
WardsDF = get_Ward(dataframe = TRUE)
WardsDF = WardsDF %>% 
  select(Longitude = long,
         Latitude = lat,
         Group = group,
         Ward)

## First total deaths = 2020-04-19 - how many? 16
##First total tests = 2020-05-19 - how many? 4363
dcmapdata = read_csv("DC_COVID-19_Cases_by_Ward.csv")
dcmapdata = dcmapdata %>% 
  mutate(WARD = str_remove_all(WARD, "Ward "),
         WARD = as.factor(WARD),
         REPORT_DATE = as.Date(REPORT_DATE)) %>% 
  select(Date = REPORT_DATE,
         Ward = WARD,
         Deaths = LIVES_LOST,
         "Positive Cases" = POSITIVE_CASES,
         "Total Tests" = TOTAL_TESTS) %>% 
  arrange(Date) %>% 
  filter(Date > as.Date("2020-01-01")) %>%
  filter(Ward == 1 | Ward == 2 | Ward == 3 | Ward == 4 | Ward == 5 |
           Ward == 6 | Ward == 7 | Ward == 8)  %>% 
  mutate(Month = format(Date, "%m"),
         Month = as.numeric(Month)) %>%
  group_by(Month, Ward) %>% 
  summarize(`Deaths` = sum(`Deaths`, na.rm = T),
                `Positive Cases` = sum(`Positive Cases`, na.rm = T),
                `Total Tests` = sum(`Total Tests`, na.rm = T)) %>%
  left_join(., WardsDF, by = "Ward") %>% 
  select(-Group)

## Plotting
mapOG = ggplot() +
  geom_polygon(data = dcmapdata, aes(x = Longitude, y = Latitude, 
                                     group = Ward, fill = `Positive Cases`), 
               color = "black") +
  geom_text(data = Wardlabs, aes(x, y, label = Ward), size = 3.5) +
  scale_fill_viridis(discrete=F, begin = 1, end = 0) + 
  coord_quickmap() +
  labs(title='Progression of COVID-19 in DC (by Ward)\nMonth:{floor(frame_time)}',
       caption = 'Source: Open Data DC') +
  
  theme(panel.background = element_rect(fill = "white", 
                                        colour = "gray", 
                                        size = 1),
        panel.grid = element_blank(),
        plot.background = element_rect(fill = "white"),
        axis.title = element_blank(),
        
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        plot.title = element_text(family = 'Times New Roman', 
                                  size = 15, color = 'black', 
                                  face = 'bold',
                                  hjust = 0.5),
        plot.subtitle = element_text(family = 'Times New Roman', 
                                     size = 11, 
                                     color = 'black', 
                                     face = 'italic', 
                                     hjust = 0.5),
        plot.caption = element_text(family = 'Times New Roman', 
                                    size = 9, 
                                    color = 'black', 
                                    face = 'italic', 
                                    hjust = 1),
        legend.title= element_text(family = 'Times New Roman', 
                                    size = 12, 
                                    color = 'black',
                                    hjust = 1),
        legend.text = element_text(family = 'Times New Roman', 
                                    size = 9, 
                                    color = 'black',
                                    hjust = 1)) +
  transition_time(`Month`) +
  labs(title='Progression of COVID-19 in DC (by Ward)\nMonth:{floor(frame_time)}',
       caption = 'Source: Open Data DC')

animate(mapOG, fps = 15, renderer = gifski_renderer("figure2.gif"))
```

# Figure 3
Data from Open Data DC: https://opendata.dc.gov/datasets/dc-covid-19-cases-by-ward
```{r message=F, error=F, warning=F}
Wardlabs = get_centroid(Ward = TRUE)
WardsDF = get_Ward(dataframe = TRUE)
WardsDF = WardsDF %>% 
  select(Longitude = long,
         Latitude = lat,
         Group = group,
         Ward)

dcmapdata = read_csv("DC_COVID-19_Cases_by_Ward.csv")
dcmapdata = dcmapdata %>% 
  mutate(WARD = str_remove_all(WARD, "Ward "),
         WARD = as.factor(WARD),
         REPORT_DATE = as.Date(REPORT_DATE)) %>% 
  select(Date = REPORT_DATE,
         Ward = WARD,
         Deaths = LIVES_LOST,
         "Positive Cases" = POSITIVE_CASES,
         "Total Tests" = TOTAL_TESTS) %>% 
  arrange(Date) %>% 
  filter(Date > as.Date("2020-01-01")) %>%
  filter(Ward == 1 | Ward == 2 | Ward == 3 | Ward == 4 | Ward == 5 |
           Ward == 6 | Ward == 7 | Ward == 8)  %>% 
  mutate(Month = format(Date, "%m"),
         Month = as.numeric(Month)) %>%
  group_by(Month, Ward) %>% 
  summarize(`Deaths` = sum(`Deaths`, na.rm = T),
                `Positive Cases` = sum(`Positive Cases`, na.rm = T),
                `Total Tests` = sum(`Total Tests`, na.rm = T)) %>%
  left_join(., WardsDF, by = "Ward") %>% 
  select(-Group)

## Plotting
mapOG = ggplot() +
  geom_polygon(data = dcmapdata, aes(x = Longitude, y = Latitude, 
                                     group = Ward, fill = `Deaths`), 
               color = "black") + 
  geom_text(data = Wardlabs, aes(x, y, label = Ward), size = 3.5) +
  scale_fill_viridis(discrete=F, begin = 1, end = 0) + 
  coord_quickmap() +
  labs(title='Deaths due to COVID-19 in DC (by Ward)\nMonth:{floor(frame_time)}',
       caption = 'Source: Open Data DC') +
  
  theme(panel.background = element_rect(fill = "white", 
                                        colour = "gray", 
                                        size = 1),
        panel.grid = element_blank(),
        plot.background = element_rect(fill = "white"),
        axis.title = element_blank(),
        
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        plot.title = element_text(
          family = 'Times New Roman', 
                                  size = 15, color = 'black', 
                                  face = 'bold',
                                  hjust = 0.5),
        plot.subtitle = element_text(family = 'Times New Roman', 
                                     size = 11, 
                                     color = 'black', 
                                     face = 'italic', 
                                     hjust = 0.5),
        plot.caption = element_text(family = 'Times New Roman', 
                                    size = 9, 
                                    color = 'black', 
                                    face = 'italic', 
                                    hjust = 1),
        legend.title= element_text(family = 'Times New Roman', 
                                    size = 12, 
                                    color = 'black',
                                    hjust = 1),
        legend.text = element_text(family = 'Times New Roman', 
                                    size = 9, 
                                    color = 'black',
                                    hjust = 1)) +
  transition_time(`Month`) +
  labs(title='Deaths due to COVID-19 in DC (by Ward)\nMonth:{floor(frame_time)}',
       caption = 'Source: Open Data DC')

animate(mapOG, fps = 15, renderer = gifski_renderer("figure3.gif"))
```


# Figure 4
Data Source: Open Data DC https://opendata.dc.gov/datasets/dc-covid-19-tested-overall
```{r message=F, error=F, warning=F}
data = read_csv('DC_COVID-19_Tested_Overall.csv')

fig4 = data %>% 
  mutate(DATE_REPORTED = as.Date(DATE_REPORTED)) %>% 
  select(Date = DATE_REPORTED,
         `Available ICU Beds` = ICU_BEDS_AVAILABLE_HOS,
         `Available Ventilators` = VENTILATORS_AVAILABLE_HOS)

x = fig4 %>% plot_ly(x = ~Date,
                 y = ~`Available ICU Beds`,
                 type = "scatter",
                 size = ~`Available ICU Beds`,
                 mode = "markers",
                 name = "Available ICU Beds",
                 text = ~paste0("There were ", `Available ICU Beds`,
                                " ICU beds available on ", 
                                format(Date, format = "%B %d, %Y")),
                 hoverinfo = "text",
                 marker = list(color = "rgb(212, 17, 89)")) %>% 

  add_trace(y = ~`Available Ventilators`,
            type = "scatter",
            size = ~`Available Ventilators`,
            mode = "markers",
            name = "Available Ventilators",
            text = ~paste0("There were ", `Available Ventilators`,
                           " ventilators available on ", 
                           format(Date, format = "%B %d, %Y")),
            hoverinfo = "text",
                 marker = list(color = "rgb(26, 133, 255)")) %>% 
  
  layout(updatemenus = list(type = "buttons",
                            label = 'Choose View',
                            buttons = list(
          list(method = "restyle",
               args = list('visible', c(TRUE, FALSE)),
               label = "Available ICU Beds"),
          list(method = "restyle",
               args = list('visible', c(FALSE, TRUE)),
               label = "Available Venrilators"))),
         xaxis = list(title = "Date", titlefont = "Times New Roman"),
         yaxis = list(title = "Number available throughout all hospitals in DC"),
         title = "Hospital Logistics in DC during COVID-19 in 2020",
         annotations = 
 list(x = 1, y = -0.1, text = "Source: Open Data DC", 
      showarrow = F, xref='paper', yref='paper', 
      xanchor='right', yanchor='auto', xshift=0, yshift=0)) 

api_create(x, filename = "ppol563_final_project_figure4")
```